#!/bin/bash

# 每日自动更新网站时间线
# 从 memory/ 和其他 .md 文件提取内容

set -e

# 颜色定义
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# 配置
REPO_DIR="$HOME/clawd/daily-journal"
MEMORY_DIR="$HOME/clawd/memory"
DATE=$(date '+%Y-%m-%d')

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  每日时间线自动更新${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

cd "$REPO_DIR"

# 1. 提取今日内容
echo -e "${YELLOW}[1/4] 提取今日内容...${NC}"

# 从 memory/YYYY-MM-DD.md 读取
TODAY_MEMORY="$MEMORY_DIR/$DATE.md"
if [ -f "$TODAY_MEMORY" ]; then
    echo -e "${GREEN}✅ 找到今日记录: $TODAY_MEMORY${NC}"

    # 提取标题（第一个 # 开头的行）
    TITLE=$(grep -m 1 "^# " "$TODAY_MEMORY" | sed 's/^# //')

    # 提取摘要（前3行非空内容）
    EXCERPT=$(grep -v "^#" "$TODAY_MEMORY" | grep -v "^$" | head -3 | tr '\n' ' ')

    # 提取标签（查找 ## 开头的小节）
    TAGS=$(grep "^## " "$TODAY_MEMORY" | sed 's/^## //' | head -5 | tr '\n' ',' | sed 's/,$//')

    # 提取洞察（查找 ### 开头的要点）
    INSIGHTS=$(grep "^### " "$TODAY_MEMORY" | sed 's/^### //' | head -3)

else
    echo -e "${YELLOW}⚠️  今日暂无记录${NC}"
    TITLE="每日记录 - $DATE"
    EXCERPT="今日暂无特别记录"
    TAGS="daily"
    INSIGHTS=""
fi

echo -e "${GREEN}✅ 标题: $TITLE${NC}"
echo -e "${GREEN}✅ 摘要: ${EXCERPT:0:100}...${NC}"

# 2. 更新 index.html
echo -e "${YELLOW}[2/4] 更新 index.html...${NC}"

# 读取当前 index.html
HTML_FILE="$REPO_DIR/index.html"

# 在 timelineData 数组的开头插入新条目
NEW_ITEM=$(cat <<EOF
            {
                date: '$DATE',
                title: '$TITLE',
                excerpt: '$EXCERPT',
                tags: ['$(echo $TAGS | sed "s/,/', '/g")'],
                insights: ['$(echo $INSIGHTS | sed "s/$/', '/g" | sed "s/', '$//")'],
                details: \`
                    <h3>📝 今日记录</h3>
                    <p>$(cat "$TODAY_MEMORY" 2>/dev/null | grep -v "^#" | grep -v "^$" | head -10 | tr '\n' ' ')</p>
                \`
            },
EOF
)

# 在 const timelineData = [ 之后插入新条目
sed -i.bak "/const timelineData = \[/a\\
$NEW_ITEM
" "$HTML_FILE"

rm -f "$HTML_FILE.bak"

echo -e "${GREEN}✅ 已更新 index.html${NC}"

# 3. Git 提交
echo -e "${YELLOW}[3/4] Git 提交...${NC}"

git add index.html
git commit -m "📝 更新每日时间线: $DATE

- $TITLE
- 自动从 memory/$DATE.md 提取
- Generated by OpenClaw AI Assistant at $(date '+%H:%M:%S')"

echo -e "${GREEN}✅ 已提交更改${NC}"

# 4. 推送到 GitHub
echo -e "${YELLOW}[4/4] 推送到 GitHub...${NC}"

git push origin main

echo -e "${GREEN}✅ 已推送到 GitHub${NC}"

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  ✅ 更新完成！${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "${BLUE}🌐 访问地址:${NC}"
echo -e "   https://jinbo007.github.io/daily-journal/"
echo ""
echo -e "${BLUE}📊 更新内容:${NC}"
echo -e "   • 日期: $DATE"
echo -e "   • 标题: $TITLE"
echo -e "   • 标签: $TAGS"
echo ""
